#!/usr/bin/env bash

sudo yabai --load-sa

terminal-notifier -message "Yabai working..."

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=dock_did_change_pref action="sudo yabai --load-sa"

yabai -m config external_bar all:0:1
yabai -m config split_ratio 0.37

function yabai_spaces () {
  displays=$(yabai -m query --displays)
  primary_display_spaces=($(echo "$displays" | jq -r '.[0].spaces[]'))
  secondary_display_spaces=($(echo "$displays" | jq -r '.[1:][] | .spaces[]'))

  for space in "${primary_display_spaces[@]}"; do
    yabai -m space $space --layout stack
  done

  for space in "${secondary_display_spaces[@]}"; do
    yabai -m space $space --layout bsp
  done
}

yabai_spaces

for event in "mission_control_exit" "display_added" "display_removed" "display_moved" "space_created" "space_destroyed"; do
  yabai -m signal --add event=$event action="source ~/.config/yabai/yabairc && yabai_spaces"
done

yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on
# (switched to https://github.com/sbmpost/AutoRaise)

# yabai -m config window_animation_duration 1
yabai -m config window_zoom_persist on

yabai -m config window_placement second_child
yabai -m config window_topmost off

yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move
# yabai -m mouse_drop_action swap

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

yabai -m rule --add app="System Settings" manage=off grid=4:4:1:1:1:1
yabai -m rule --add app="Finder" manage="off" grid="9:16:1:2:8:6"
# yabai -m rule --add app="Karabiner-Elements" sticky=on layer=above manage=off
# yabai -m rule --add app="Karabiner-EventViewer" sticky=on layer=above manage=off
# yabai -m rule --add app="Finder" sticky=on layer=above manage=off
# yabai -m rule --add app="Disk Utility" sticky=on layer=above manage=off
# yabai -m rule --add app="System Information" sticky=on layer=above manage=off
# yabai -m rule --add app="Activity Monitor" sticky=on layer=above manage=off
# yabai -m rule --add app="Cisco Webex Start" manage=off
# yabai -m rule --add app="Private Internet Access" manage=off
# yabai -m rule --add app="DeepL" manage=off
# yabai -m rule --add app="Keychain Access" manage=off
# yabai -m rule --add app="Preview" manage=off
# yabai -m rule --add app="iScreen Shoter" manage=off
# yabai -m rule --add app="Xnip" manage=off
# yabai -m rule --add app="App Store" manage=off
# yabai -m rule --add app="Stats" manage=off
# yabai -m rule --add app="Color Picker" manage=off

# Safari settings
# yabai -m rule --add app="Safari" title="General" manage=off
# yabai -m rule --add app="Safari" title="Tabs" manage=off
# yabai -m rule --add app="Safari" title="AutoFill" manage=off
# yabai -m rule --add app="Safari" title="Passwords" manage=off
# yabai -m rule --add app="Safari" title="Search" manage=off
# yabai -m rule --add app="Safari" title="Security" manage=off
# yabai -m rule --add app="Safari" title="Privacy" manage=off
# yabai -m rule --add app="Safari" title="Websites" manage=off
# yabai -m rule --add app="Safari" title="Extensions" manage=off
# yabai -m rule --add app="Safari" title="Advanced" manage=off

