#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

DISPLAY_COUNT=$(yabai -m query --displays | jq length)

yabai -m config external_bar all:0:1

for event in "mission_control_exit" "display_added" "display_removed" "display_moved"; do
  yabai -m signal --add event=$event action="~/.yabai_configure_space_layouts.sh"
done

yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on

# yabai -m config window_animation_duration 1
yabai -m config window_zoom_persist on

yabai -m config window_placement second_child
yabai -m config window_topmost off

yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move
# yabai -m mouse_drop_action swap

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

yabai -m rule --add app="System Settings" sticky=on layer=above manage=off
yabai -m rule --add app="Karabiner-Elements" sticky=on layer=above manage=off
yabai -m rule --add app="Karabiner-EventViewer" sticky=on layer=above manage=off
yabai -m rule --add app="Finder" sticky=on layer=above manage=off
yabai -m rule --add app="Disk Utility" sticky=on layer=above manage=off
yabai -m rule --add app="System Information" sticky=on layer=above manage=off
yabai -m rule --add app="Activity Monitor" sticky=on layer=above manage=off
yabai -m rule --add app="Cisco Webex Start" manage=off
yabai -m rule --add app="Private Internet Access" manage=off
yabai -m rule --add app="DeepL" manage=off
yabai -m rule --add app="Keychain Access" manage=off
yabai -m rule --add app="Preview" manage=off
yabai -m rule --add app="iScreen Shoter" manage=off
yabai -m rule --add app="Xnip" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="Color Picker" manage=off
yabai -m rule --add app="Archive Utility" manage=off
yabai -m rule --add app="Photo Booth" manage=off

# Safari settings
yabai -m rule --add app="Safari" title="General" manage=off
yabai -m rule --add app="Safari" title="Tabs" manage=off
yabai -m rule --add app="Safari" title="AutoFill" manage=off
yabai -m rule --add app="Safari" title="Passwords" manage=off
yabai -m rule --add app="Safari" title="Search" manage=off
yabai -m rule --add app="Safari" title="Security" manage=off
yabai -m rule --add app="Safari" title="Privacy" manage=off
yabai -m rule --add app="Safari" title="Websites" manage=off
yabai -m rule --add app="Safari" title="Extensions" manage=off
yabai -m rule --add app="Safari" title="Advanced" manage=off
