#!/usr/bin/env sh

# Load scripting addition on restart
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Global settings
yabai -m config \
    active_window_opacity 1.0 \
    auto_balance on \
    bottom_padding 12 \
    left_padding 12 \
    right_padding 12 \
    top_padding 12 \
    window_gap 12 \
    debug_output on \
    display_arrangement_order default \
    external_bar off:40:0 \
    insert_feedback_color 0xffd75f5f \
    layout float \
    menubar_opacity 1.0 \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    mouse_follows_focus on \
    focus_follows_mouse autofocus \
    mouse_modifier cmd \
    normal_window_opacity 0.70 \
    split_ratio 0.50 \
    split_type auto \
    window_animation_duration 0.0 \
    window_animation_easing ease_out_circ \
    window_opacity off \
    window_opacity_duration 0.0 \
    window_origin_display default \
    window_placement second_child \
    window_shadow on \
    window_zoom_persist on

# Default: all applications are in the normal layer
yabai -m rule --add app=".*" layer=normal

# Ensure Preview stays normal
yabai -m rule --add title="^Preview" layer=normal

# Raycast should always be on top
yabai -m rule --add app="Raycast" layer=above sub-layer=2

# iPhone Mirroring should be above other apps but below Raycast
yabai -m rule --add title="iPhone Mirroring" layer=above sub-layer=1

